import app from '@/app';

function Status(request, response) {
  response.status(200);
  response.json([{
      id: 101,
      uf: 'MS',
      subsecao: 'Campo Grande',
      feriados: [],
    },
    {
      id: 102,
      uf: 'MS',
      subsecao: 'Dourados',
      feriados: [],
    },
    {
      id: 103,
      uf: 'MS',
      subsecao: 'Corumbá',
      feriados: [],
    },
    {
      id: 104,
      uf: 'MS',
      subsecao: 'Coxim',
      feriados: [],
    },
    {
      id: 105,
      uf: 'MS',
      subsecao: 'Três Lagoas',
      feriados: [],
    },
    {
      id: 106,
      uf: 'MS',
      subsecao: 'Ponta Porã',
      feriados: [],
    },
    {
      id: 107,
      uf: 'MS',
      subsecao: 'Naviraí',
      feriados: [],
    },
    {
      id: 108,
      uf: 'SP',
      subsecao: 'Barueri ',
      feriados: [],
    },
    {
      id: 109,
      uf: 'SP',
      subsecao: 'Bauru ',
      feriados: [],
    },
    {
      id: 110,
      uf: 'SP',
      subsecao: 'Botucatu ',
      feriados: [],
    },
    {
      id: 111,
      uf: 'SP',
      subsecao: 'Bragança Paulista ',
      feriados: [],
    },
    {
      id: 112,
      uf: 'SP',
      subsecao: 'Campinas ',
      feriados: [],
    },
    {
      id: 113,
      uf: 'SP',
      subsecao: 'Caraguatatuba ',
      feriados: [],
    },
    {
      id: 114,
      uf: 'SP',
      subsecao: 'Catanduva ',
      feriados: [],
    },
    {
      id: 115,
      uf: 'SP',
      subsecao: 'Franca ',
      feriados: [],
    },
    {
      id: 116,
      uf: 'SP',
      subsecao: 'Guaratinguetá ',
      feriados: [],
    },
    {
      id: 117,
      uf: 'SP',
      subsecao: 'Guarulhos ',
      feriados: [],
    },
    {
      id: 118,
      uf: 'SP',
      subsecao: 'Itapeva ',
      feriados: [],
    },
    {
      id: 119,
      uf: 'SP',
      subsecao: 'Jales ',
      feriados: [],
    },
    {
      id: 120,
      uf: 'SP',
      subsecao: 'Jaú ',
      feriados: [],
    },
    {
      id: 121,
      uf: 'SP',
      subsecao: 'Jundiaí ',
      feriados: [],
    },
    {
      id: 122,
      uf: 'SP',
      subsecao: 'Limeira ',
      feriados: [],
    },
    {
      id: 123,
      uf: 'SP',
      subsecao: 'Lins ',
      feriados: [],
    },
    {
      id: 124,
      uf: 'SP',
      subsecao: 'Marília ',
      feriados: [],
    },
    {
      id: 125,
      uf: 'SP',
      subsecao: 'Mauá ',
      feriados: [],
    },
    {
      id: 126,
      uf: 'SP',
      subsecao: 'Mogi das Cruzes ',
      feriados: [],
    },
    {
      id: 127,
      uf: 'SP',
      subsecao: 'Osasco ',
      feriados: [],
    },
    {
      id: 128,
      uf: 'SP',
      subsecao: 'Ourinhos ',
      feriados: [],
    },
    {
      id: 129,
      uf: 'SP',
      subsecao: 'Piracicaba ',
      feriados: [],
    },
    {
      id: 130,
      uf: 'SP',
      subsecao: 'Presidente Prudente ',
      feriados: [],
    },
    {
      id: 131,
      uf: 'SP',
      subsecao: 'Registro ',
      feriados: [],
    },
    {
      id: 132,
      uf: 'SP',
      subsecao: 'Ribeirão Preto ',
      feriados: [],
    },
    {
      id: 133,
      uf: 'SP',
      subsecao: 'Santo André ',
      feriados: [],
    },
    {
      id: 134,
      uf: 'SP',
      subsecao: 'Santos ',
      feriados: [],
    },
    {
      id: 135,
      uf: 'SP',
      subsecao: 'São Bernardo do Campo ',
      feriados: [],
    },
    {
      id: 136,
      uf: 'SP',
      subsecao: 'São Carlos ',
      feriados: [],
    },
    {
      id: 137,
      uf: 'SP',
      subsecao: 'São João da Boa Vista ',
      feriados: [],
    },
    {
      id: 138,
      uf: 'SP',
      subsecao: 'São José do Rio Preto ',
      feriados: [],
    },
    {
      id: 139,
      uf: 'SP',
      subsecao: 'São José dos Campos ',
      feriados: [],
    },
    {
      id: 140,
      uf: 'SP',
      subsecao: 'São Paulo ',
      feriados: [],
    },
    {
      id: 141,
      uf: 'SP',
      subsecao: 'São Vicente ',
      feriados: [],
    },
    {
      id: 142,
      uf: 'SP',
      subsecao: 'Sorocaba ',
      feriados: [],
    },
    {
      id: 143,
      uf: 'SP',
      subsecao: 'Taubaté ',
      feriados: [],
    },
    {
      id: 144,
      uf: 'SP',
      subsecao: 'Tupã ',
      feriados: [],
    }]);
}

export default app().get(Status);
